# Generated by Django 5.0.2 on 2024-02-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('home_appliance', models.CharField(choices=[('Refrigerator', 'Refrigerator'), ('Stove with Oven', 'Stove with Oven'), ('Oven', 'Oven'), ('Dish Washer', 'Dish Washer'), ('Washer', 'Washer'), ('Dryer', 'Dryer')], max_length=15)),
                ('home_appliance_maker', models.CharField(max_length=15)),
                ('home_appliance_model_number', models.CharField(max_length=30)),
                ('home_appliance_problem', models.TextField()),
            ],
        ),
    ]
